---
title: "Exploratory Data Analysis"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

The video below discusses the common steps when investigating data. This is usually referred to as an exploratory data analysis (EDA).  

I highly recommend watching the video using the 'full' Panopto player. There is a 'pop out' button in the bottom right of the video to enter this viewer.

```{=html}
<iframe src="https://ncsu.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=6bb5d60f-a161-44c8-abd0-b0f0014391fb&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="Course Goals" ></iframe>
```

## Notes

- <a href = "13-EDA.html" target = "_blank">HTML version</a>
- <a href = "PDFs/13-EDA.pdf" target = "_blank">PDF version</a>


EDA

Exploratory Data Analysis (EDA) is often the first step of dealing with data.  However, EDA is somewhat of an art and something that you get better at with experience.  Often people new to EDA don't know what they should be looking for!  Here are some articles that discuss different strategies for EDA.

        https://shopify.engineering/conducting-exploratory-data-analysis
        https://www.ibm.com/cloud/learn/exploratory-data-analysis
        https://en.wikipedia.org/wiki/Exploratory_data_analysis
        https://www.itl.nist.gov/div898/handbook/eda/section1/eda11.htm

Modeling Basics

Here are some useful resources for learning about modeling, metrics, etc.

    ISLR book (opens in new window): Read section (Big picture ideas) 2.1, 2.2, (Basic regression) 3.1, 3.2, 3.3, (CV) 5.1, (Regularized models) 6.2
    Google's open course materials has information about these models, loss functions, metrics, etc: https://developers.google.com/machine-learning/crash-course/classification/video-lecture (opens in new window)
    LASSO basics in python (opens in new window)


Use the table of contents on the left or the arrows at the bottom of this page to navigate to the next learning material!