---
title: "Common Uses for Data"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

The video below discusses the common ways we use data.  We discuss the general idea of statistical learning and using data for descriptive purposes, for predictive purposes, in order to make statistical inferences, and to find patterns in data.

I highly recommend watching the video using the 'full' Panopto player. There is a 'pop out' button in the bottom right of the video to enter this viewer.

```{=html}
<iframe src="https://ncsu.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=6bb5d60f-a161-44c8-abd0-b0f0014391fb&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="Course Goals" ></iframe>
```

## Notes

- <a href = "07-Common_Uses_For_Data.html" target = "_blank">HTML version</a>
- <a href = "PDFs/07-Common_Uses_For_Data.pdf" target = "_blank">PDF version</a>

Use the table of contents on the left or the arrows at the bottom of this page to navigate to the next learning material!


Modeling Basics

Here are some useful resources for learning about modeling, metrics, etc.

    ISLR book (opens in new window): Read section (Big picture ideas) 2.1, 2.2, (Basic regression) 3.1, 3.2, 3.3, (CV) 5.1, (Regularized models) 6.2
    Google's open course materials has information about these models, loss functions, metrics, etc: https://developers.google.com/machine-learning/crash-course/classification/video-lecture (opens in new window)
    LASSO basics in python (opens in new window)
