---
title: "LASSO Models"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

The video below describes the Least Angle Subset and Selection Operator (LASSO). This is a method for fitting an MLR type model with a penalty term involved. This clever penalty term shrinks the coefficients estimates towards zero, setting some coefficient estimates exactly to zero (hence doing variable selection). This model also introduces the notion of a **tuning** parameter. This tuning parameter must be selected and is usually done so using CV.

I highly recommend watching the video using the 'full' Panopto player. There is a 'pop out' button in the bottom right of the video to enter this viewer.

```{=html}
<iframe src="https://ncsu.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=fcbd6527-87df-4748-9f13-b10a013da04d&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="27-LASSO Models" ></iframe>
```

## Notes

- <a href = "29-LASSO.html" target = "_blank">HTML version</a>
- <a href = "PDFs/29-LASSO.pdf" target = "_blank">PDF version</a>

This wraps up the material for week 5! Your first project (along with the exam this week) is the next big assessment.

Use the table of contents on the left or the arrows at the bottom of this page to navigate to the next learning material!