project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - about.qmd
    - 01_Programming_in_python/01-Course_Goals_Landing.qmd
    - 01_Programming_in_python/02-Basic_Use_Of_Python.ipynb
    - 01_Programming_in_python/03-Modules.ipynb
    - 01_Programming_in_python/04-JupyterLab_Notebooks_Markdown.ipynb
    - 01_Programming_in_python/05-List_Basics_Strings.ipynb
    - 01_Programming_in_python/06-Numeric_Types_Booleans.ipynb
    - 01_Programming_in_python/07-Common_Uses_For_Data_Landing.qmd
    - 01_Programming_in_python/08-User_Defined_Functions.ipynb
    - 01_Programming_in_python/09-Control_Flow.ipynb
    - 01_Programming_in_python/10-Lists_Tuples.ipynb
    - 01_Programming_in_python/11-Dictionaries.ipynb
    - 01_Programming_in_python/12-Numpy.ipynb
    - 01_Programming_in_python/13-EDA_Landing.qmd
    - 01_Programming_in_python/14-Pandas_Series.ipynb
    - 01_Programming_in_python/15-Pandas_Data_Frames.ipynb
    - 01_Programming_in_python/16-Pandas_For_Reading_Data.ipynb
    - 01_Programming_in_python/17-Numerical_Summaries.ipynb
    - 01_Programming_in_python/18-More_Function_Writing.ipynb
    - 01_Programming_in_python/19-Plotting_matplotlib.ipynb
    - 01_Programming_in_python/20-Plotting_pandas.ipynb
    - 01_Programming_in_python/21-Error_Handling.ipynb
    - 01_Programming_in_python/22-Big_Recap_Landing.qmd
    - 01_Programming_in_python/23-Fitting_Evaluating_SLR_Models_Landing.qmd
    - 01_Programming_in_python/24-Prediction_Testing_Training_Landing.qmd
    - 01_Programming_in_python/25-Cross_Validation_Landing.qmd
    - 01_Programming_in_python/26-Multiple_Linear_Regression_Landing.qmd
    - 01_Programming_in_python/27-LASSO_Landing.qmd
    - 01_Programming_in_python/Learning_Python.ipynb
    - 02_Big_Data_Management/01-Big_Data_Basics_Landing.qmd
    - 02_Big_Data_Management/02-Role_of_Statistics_Landing.qmd
    - 02_Big_Data_Management/03-Databases_SQL.ipynb
    - 02_Big_Data_Management/04-SQL_Joins_Landing.qmd
    - 02_Big_Data_Management/05-SQL_Resources.qmd
    - 02_Big_Data_Management/06-Data_Pipelines_Storage_Landing.qmd
    - 02_Big_Data_Management/07-Legacy_Software_HDFS_Landing.qmd
    - 02_Big_Data_Management/08-Connecting_to_JupyterHub.qmd
    - 02_Big_Data_Management/09-Spark_for_Big_Data_Landing.qmd
    - 02_Big_Data_Management/10-pyspark_RDD_Landing.qmd
    - 02_Big_Data_Management/11-pyspark_pandas_on_Spark_Landing.qmd
    - 02_Big_Data_Management/12-pyspark_Spark_SQL_Landing.qmd
    - 02_Big_Data_Management/SQL_Joins_Notebook.ipynb
    - 03_Modeling_Data/01-Modeling_Data_Recap_Landing.qmd
    - 03_Modeling_Data/02-Modeling_Example_Landing.qmd
    - 03_Modeling_Data/03-Logistic_Regression_Basics_Landing.qmd
    - 03_Modeling_Data/04-Logistic_Regression_Extensions_Landing.qmd
    - 03_Modeling_Data/05-Regularized_Regression_Landing.qmd
    - 03_Modeling_Data/06-Loss_Functions_and_Model_Metrics_Landing.qmd
    - 03_Modeling_Data/07-Classification_And_Regression_Trees_Landing.qmd
    - 03_Modeling_Data/08-Bagging_And_Random_Forests_Landing.qmd
    - 03_Modeling_Data/09-kNN_Landing.qmd
    - 03_Modeling_Data/10-MLLibBasics_Landing.qmd
    - 03_Modeling_Data/11-MLPipelines_Landing.qmd
    - 03_Modeling_Data/12-MLflow_Landing.qmd
    - 03_Modeling_Data/13-MLOps_Landing.qmd
    - 03_Modeling_Data/MLLib_MLflow.ipynb
    - 03_Modeling_Data/02-Modeling_Example.ipynb
    - 04_Streaming_Data/01-Streaming_Data_Concepts_Landing.qmd
    - 04_Streaming_Data/02-Common_Streaming_Tasks.ipynb
    - 04_Streaming_Data/03-Spark_Structured_Streaming_Landing.qmd
    - 04_Streaming_Data/04-Reading_Writing_Streams_With_Spark_Structured_Streaming_Landing.qmd
    - 04_Streaming_Data/05-Transformations_Windowing_Aggregations_Landing.qmd
    - 04_Streaming_Data/06-Streaming_Joins_Landing.qmd
website:
  title: "ST 554 Analysis of Big Data (with Python)"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/jbpost2/ST-554-Big-Data-With-Python
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - index.qmd
      - section: "Topic 1: Learning `python`"
        contents:
          - 01_Programming_in_python/01-Course_Goals_Landing.qmd
          - 01_Programming_in_python/02-Basic_Use_Of_Python.ipynb
          - 01_Programming_in_python/03-Modules.ipynb
          - 01_Programming_in_python/04-JupyterLab_Notebooks_Markdown.ipynb
          - 01_Programming_in_python/05-List_Basics_Strings.ipynb
          - 01_Programming_in_python/06-Numeric_Types_Booleans.ipynb
          - 01_Programming_in_python/07-Common_Uses_For_Data_Landing.qmd
          - 01_Programming_in_python/08-User_Defined_Functions.ipynb
          - 01_Programming_in_python/09-Control_Flow.ipynb
          - 01_Programming_in_python/10-Lists_Tuples.ipynb
          - 01_Programming_in_python/11-Dictionaries.ipynb
          - 01_Programming_in_python/12-Numpy.ipynb
      - section: "Topic 2: Dealing with Data in `python`"
        contents:
          - 01_Programming_in_python/13-EDA_Landing.qmd
          - 01_Programming_in_python/14-Pandas_Series.ipynb
          - 01_Programming_in_python/15-Pandas_Data_Frames.ipynb
          - 01_Programming_in_python/16-Pandas_For_Reading_Data.ipynb
          - 01_Programming_in_python/17-Numerical_Summaries.ipynb
          - 01_Programming_in_python/18-More_Function_Writing.ipynb
          - 01_Programming_in_python/19-Plotting_matplotlib.ipynb
          - 01_Programming_in_python/20-Plotting_pandas.ipynb
          - 01_Programming_in_python/21-Error_Handling.ipynb
      - section: "Topic 3: Basics of Predictive Modeling"
        contents:
          - 01_Programming_in_python/22-Big_Recap_Landing.qmd
          - 01_Programming_in_python/23-Fitting_Evaluating_SLR_Models_Landing.qmd
          - 01_Programming_in_python/24-Prediction_Testing_Training_Landing.qmd
          - 01_Programming_in_python/25-Cross_Validation_Landing.qmd
          - 01_Programming_in_python/26-Multiple_Linear_Regression_Landing.qmd
          - 01_Programming_in_python/27-LASSO_Landing.qmd
      - section: "Topic 4: Big Data Management"
        contents:
          - 02_Big_Data_Management/01-Big_Data_Basics_Landing.qmd
          - 02_Big_Data_Management/02-Role_of_Statistics_Landing.qmd
          - 02_Big_Data_Management/03-Databases_SQL.ipynb
          - 02_Big_Data_Management/04-SQL_Joins_Landing.qmd
          - 02_Big_Data_Management/05-SQL_Resources.qmd
          - 02_Big_Data_Management/06-Data_Pipelines_Storage_Landing.qmd
          - 02_Big_Data_Management/07-Legacy_Software_HDFS_Landing.qmd
          - 02_Big_Data_Management/08-Connecting_to_JupyterHub.qmd
          - 02_Big_Data_Management/09-Spark_for_Big_Data_Landing.qmd
          - 02_Big_Data_Management/10-pyspark_RDD_Landing.qmd
          - 02_Big_Data_Management/11-pyspark_pandas_on_Spark_Landing.qmd
          - 02_Big_Data_Management/12-pyspark_Spark_SQL_Landing.qmd
      - section: "Topic 5: Modeling Data"
        contents:
          - 03_Modeling_Data/01-Modeling_Data_Recap_Landing.qmd
          - 03_Modeling_Data/02-Modeling_Example_Landing.qmd
          - 03_Modeling_Data/03-Logistic_Regression_Basics_Landing.qmd
          - 03_Modeling_Data/04-Logistic_Regression_Extensions_Landing.qmd
          - 03_Modeling_Data/05-Regularized_Regression_Landing.qmd
          - 03_Modeling_Data/06-Loss_Functions_and_Model_Metrics_Landing.qmd
          - 03_Modeling_Data/07-Classification_And_Regression_Trees_Landing.qmd
          - 03_Modeling_Data/08-Bagging_And_Random_Forests_Landing.qmd
          - 03_Modeling_Data/09-kNN_Landing.qmd
          - 03_Modeling_Data/10-MLLibBasics_Landing.qmd
          - 03_Modeling_Data/11-MLPipelines_Landing.qmd
          - 03_Modeling_Data/12-MLflow_Landing.qmd
          - 03_Modeling_Data/13-MLOps_Landing.qmd
      - section: "Topic 6: Streaming Data"
        contents:
          - 04_Streaming_Data/01-Streaming_Data_Concepts_Landing.qmd
          - 04_Streaming_Data/02-Common_Streaming_Tasks.ipynb
          - 04_Streaming_Data/03-Spark_Structured_Streaming_Landing.qmd
          - 04_Streaming_Data/04-Reading_Writing_Streams_With_Spark_Structured_Streaming_Landing.qmd
          - 04_Streaming_Data/05-Transformations_Windowing_Aggregations_Landing.qmd
          - 04_Streaming_Data/06-Streaming_Joins_Landing.qmd
  page-navigation: true
  reader-mode: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px
      
callout-appearance: simple

date: today
date-format: iso


