---
title: "Big Data Basics"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

The video below gives a definition of big data and discusses common issues that arise when dealing with big data.

I highly recommend watching the video using the 'full' Panopto player. There is a 'pop out' button in the bottom right of the video to enter this viewer.

**update video**
```{=html}
<iframe src="https://ncsu.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=ae82211f-546d-4e2d-9c91-b0fe018434ea&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="13-EDA" ></iframe>
```

## Notes

- <a href = "01-Big_Data_Basics.html" target = "_blank">HTML version</a>
- <a href = "PDFs/01-Big_Data_Basics.pdf" target = "_blank">PDF version</a>


## Additional Readings for Week 7

### The Big Data Paradigm

- <a href="https://www.sciencedirect.com/science/article/pii/S0268401214001066" target="_blank">Academic overview</a>
- <a href="https://www.suse.com/c/rancher_blog/an-introduction-to-big-data-concepts/" target="_blank">Overview 2</a> (Suse)
- <a href="https://www.oracle.com/big-data/what-is-big-data/" target="_blank">Overview 3</a> (Oracle)

### Databases

- <a href="https://towardsdatascience.com/difference-between-sql-and-nosql-42a194b8c56c/" target="_blank">Basics of Databases</a>(SQL and NoSQL)
- <a href="https://www.oracle.com/database/what-is-database/" target="_blank">What is a database?</a>, what is a <a href="https://www.oracle.com/database/what-is-a-relational-database/" target="_blank">relational database</a>? (Oracle)
- <a href="https://realpython.com/python-sql-libraries/" target="_blank">Python SQL Libraries</a> (realpython - a nice site but some stuff goes out of date!)
- <a href="https://pynative.com/python-sqlite/" target="_blank">SQLite in python</a> (tutorial from pynative.com)
- <a href="https://www.sqlite.org/schematab.html" target="_blank">SQLite schema table</a> (sqlite.org documentation - a lot of other useful stuff there)
- <a href="https://learnsql.com/blog/how-to-join-3-tables-or-more-in-sql/" target="_blank">Three plus table joins</a> (learnsql.com)

### Data Storage

- The <a href="https://stackoverflow.com/questions/43524694/where-does-big-data-go-and-how-is-it-stored" target="_blank" style="background-color: rgb(255, 255, 255); font-size: 0.9375rem;">first answer here</a> is useful to read
- Data Warehouses: <a href="https://www.oracle.com/database/what-is-a-data-warehouse/" target="_blank">Article 1</a> (Oracle), <a href="https://aws.amazon.com/data-warehouse/" target="_blank">Article 2</a> (Amazon)
- Databases and Data Warehouses: <a href="https://www.healthcatalyst.com/insights/database-vs-data-warehouse-a-comparative-review/" target="_blank">Article 1</a>, <a href="https://panoply.io/data-warehouse-guide/the-difference-between-a-database-and-a-data-warehouse/" target="_blank">Article 2</a>
- <a href="https://www.ibm.com/cloud/learn/data-mart#:~:text=A%20data%20mart%20is%20a,through%20an%20entire%20data%20warehouse." target="_blank">Data Marts</a> (IBM)
- <a href="https://blogs.sas.com/content/datamanagement/2017/04/27/mdm-different-data-warehousing/" target="_blank">MDM</a> (SAS)
- Databases, Data Warehouses, and Data Lake: <a href="https://venturebeat.com/2021/04/28/understanding-when-to-use-a-database-data-lake-or-data-warehouse/" target="_blank">Article 1</a>, <a href="https://www.bmc.com/blogs/data-lake-vs-data-warehouse-vs-database-whats-the-difference/" target="_blank">Article 2</a>, <a href="https://www.sas.com/en_us/insights/articles/data-management/data-lake-and-data-warehouse-know-the-difference.html" target="_blank">Article 3</a>
- Data Lakes: <a href="https://lakefs.io/data-lakes/" target="_blank" style="background-color: rgb(255, 255, 255); font-size: 0.9375rem;">Article 1,</a> <a href="https://www.sas.com/en_us/insights/articles/data-management/data-lake-and-data-warehouse-know-the-difference.html" target="_blank">Article 2</a>
- <a href="https://databricks.com/blog/2020/01/30/what-is-a-data-lakehouse.html" target="_blank">Lake House</a> (databricks - they actually have a lot of useful training resources as well!)

### Big Data Storage

- Data pipelines: <a href="https://streamsets.com/learn/data-pipelines/" target="_blank">Article 1,</a> <a href="https://medium.com/world-of-iot/93-understanding-the-basics-of-any-iot-data-pipeline-from-ingress-capture-to-processing-to-7538a5632478" target="_blank">Article 2</a>


Use the table of contents on the left or the arrows at the bottom of this page to navigate to the next learning material!