---
title: "Legacy Big Data Software: Hadoop Distributed File System"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

The video below discusses a legacy big data software called Hadoop along with the common Map-Reduce actions that Hadoop allows one to perform on big data. While not a widely used software at this point, understanding the language and ideas of what made Hadoop popular are important. 

I highly recommend watching the video using the 'full' Panopto player. There is a 'pop out' button in the bottom right of the video to enter this viewer.

**Update video**
```{=html}
<iframe src="https://ncsu.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=ae82211f-546d-4e2d-9c91-b0fe018434ea&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="13-EDA" ></iframe>
```

## Notes

- <a href = "08-Legacy_Software_HDFS.html" target = "_blank">HTML version</a>
- <a href = "PDFs/08-Legacy_Software_HDFS.pdf" target = "_blank">PDF version</a>


## Additional Readings for Week 8

### Hadoop

- Hadoop YARN: <a href="https://hadoop.apache.org/docs/r3.3.1/hadoop-yarn/hadoop-yarn-site/YARN.html" target="_blank">Docs</a>, <a href="https://www.geeksforgeeks.org/hadoop-yarn-architecture/" target="_blank">Article</a>
- HDFS &amp; the Cloud: <a href="https://cloud.google.com/blog/products/storage-data-transfer/hdfs-vs-cloud-storage-pros-cons-and-migration-tips" target="_blank">Article 1</a>, <a href="https://www.oreilly.com/library/view/moving-hadoop-to/9781491959626/" target="_blank">Book</a> (not free though)
- <a href="https://blogs.oracle.com/bigdata/post/what-is-object-storage" target="_blank">Object Storage with Apache Spark</a>&nbsp;(we won't cover this but it may be more common going forward)
- <a href="https://aws.amazon.com/s3/" target="_blank">S3 storage</a>
- <a href="https://hevodata.com/learn/hadoop-s3-comparison/" target="_blank">Hadoop vs S3</a>
- <a href="https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction" target="_blank">Azure Blob Storage</a>

### MapReduce

- MapReduce Examples: <a href="https://www.todaysoftmag.com/article/1358/hadoop-mapreduce-deep-diving-and-tuning" target="_blank">Article 1</a>, <a href="https://www.geeksforgeeks.org/map-reduce-in-hadoop/?ref=lbp" target="_blank">Article 2</a>
- A <a href="https://nyu-cds.github.io/python-bigdata/01-introduction/" target="_blank">good intro through</a> an example using PySpark<br>
- <a href="https://www.ibm.com/cloud/blog/hadoop-vs-spark#:~:text=Spark%20is%20a%20Hadoop%20enhancement,to%20100x%20faster%20than%20MapReduce." target="_blank">Hadoop vs Spark</a>

### Spark

- <a href="https://aws.amazon.com/big-data/what-is-spark/" target="_blank">What is spark?</a>
- Basics of Spark: <a href="https://www.tutorialspoint.com/pyspark/index.htm" target="_blank">Article 1</a>, <a href="https://www.tutorialspoint.com/apache_spark/index.htm" target="_blank" style="background-color: rgb(255, 255, 255); font-size: 0.9375rem;">Article 2</a>, <a href="https://realpython.com/pyspark-intro/" target="_blank" style="background-color: rgb(255, 255, 255); font-size: 0.9375rem;">Article 3</a>, <a href="https://databricks.com/session/not-your-fathers-database-how-to-use-apache-spark-properly-in-your-big-data-architecture" target="_blank" style="background-color: rgb(255, 255, 255); font-size: 0.9375rem;">Article 4</a>
- <a href="https://databricks.com/blog/2016/07/14/a-tale-of-three-apache-spark-apis-rdds-dataframes-and-datasets.html" target="_blank">Spark APIs</a>
- <a href="https://data-flair.training/blogs/dag-in-apache-spark/#:~:text=It%20is%20a%20programming%20style,does%20not%20write%20to%20disk." target="_blank">More on DAGs</a>
- <a href="https://intellipaat.com/blog/tutorial/spark-tutorial/spark-and-rdd-cheat-sheet/" target="_blank">Spark cheat sheet</a>


Use the table of contents on the left or the arrows at the bottom of this page to navigate to the next learning material!