---
title: "`pyspark`: Resilient Distributed Data Sets"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

The video below describes the underlying data structure in `spark` called the *resilient distributed data* (RDD) data set. While we rarely utilize these data structures and their functionality exactly, it is useful to have an idea about RDDs and the functionality they have.

I highly recommend watching the video using the 'full' Panopto player. There is a 'pop out' button in the bottom right of the video to enter this viewer.

**update video**
```{=html}
<iframe src="https://ncsu.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=ae82211f-546d-4e2d-9c91-b0fe018434ea&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="13-EDA" ></iframe>
```

## Notes

- <a href = "10-pyspark_RDD.html" target = "_blank">HTML version</a>
- <a href = "PDFs/10-pyspark_RDD.pdf" target = "_blank">PDF version</a>


## Additional Readings for Week 3

Exploratory Data Analysis (EDA) is often the first step of dealing with data.  However, EDA is somewhat of an art and something that you get better at with experience.  Often people new to EDA don't know what they should be looking for!  Here are some articles that discuss different strategies for EDA.

- <a href = "https://shopify.engineering/conducting-exploratory-data-analysis" target = "_blank">Shopify page</a>
- <a href = "https://www.ibm.com/cloud/learn/exploratory-data-analysis" target = "_blank">IBM page</a>
- <a href = "https://en.wikipedia.org/wiki/Exploratory_data_analysis" target = "_blank">Wikipedia page</a>
- <a href = "https://www.itl.nist.gov/div898/handbook/eda/section1/eda11.htm" target = "_blank">NIST page</a>

Use the table of contents on the left or the arrows at the bottom of this page to navigate to the next learning material!