---
title: "`pyspark`: Spark SQL"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

The video below discusses how `pyspark` can be used using its SQL style data frame and functionality. 

I highly recommend watching the video using the 'full' Panopto player. There is a 'pop out' button in the bottom right of the video to enter this viewer.

The `pyspark` code used in the notes and the example done at the end of the notes is <a href = "pyspark_notebook.ipynb" target = "_blank">available in this notebook</a>. You'll need to download this `.ipynb` file and upload it to your `JupyterHub` environment. Make sure that the kernel used to run the notebook is a `pyspark` kernel!

**update video**
```{=html}
<iframe src="https://ncsu.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=ae82211f-546d-4e2d-9c91-b0fe018434ea&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="13-EDA" ></iframe>
```

If you are not an NC State student, you can download docker and gain access to [Spark with a Jupyter notebook interface](https://hub.docker.com/r/jupyter/all-spark-notebook) reasonably quickly! 

## Notes

- <a href = "12-pyspark_Spark_SQL.html" target = "_blank">HTML version</a>
- <a href = "PDFs/12-pyspark_Spark_SQL.pdf" target = "_blank">PDF version</a>

Use the table of contents on the left or the arrows at the bottom of this page to navigate to the next learning material!