---
title: "`pyspark`: Pandas-on-Spark"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

The video below discusses the use of `pyspark` and the `pandas-on-spark` framework. This utilizes a `pandas` style data frame and functionality.

I highly recommend watching the video using the 'full' Panopto player. There is a 'pop out' button in the bottom right of the video to enter this viewer.

The `pyspark` code used in the notes and the example done at the end of the notes is <a href = "pyspark_notebook.ipynb" target = "download">available in this notebook</a>. You'll need to download this `.ipynb` file and upload it to your `JupyterHub` environment. Make sure that the kernel used to run the notebook is a `pyspark` kernel!

Remember, if you are off campus you should log in to the VPN and then you can <a href ="https://jhub.cos.ncsu.edu/" target = "_blank">access our `JupyterHub`</a>.

```{=html}
<iframe src="https://ncsu.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=d54fc677-e6e3-48d2-8967-b29500cda5da&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="11-pyspark_pandas-on-spark" ></iframe>
```

If you are not an NC State student, you can download docker and gain access to <a href = "https://hub.docker.com/r/jupyter/all-spark-notebook" target = "_blank">Spark with a Jupyter notebook interface</a> reasonably quickly!

## Notes

- <a href = "13-pyspark_pandas_on_Spark.html" target = "_blank">HTML version</a>
- <a href = "PDFs/13-pyspark_pandas_on_Spark.pdf" target = "_blank">PDF version</a>

Use the table of contents on the left or the arrows at the bottom of this page to navigate to the next learning material!