---
title: "Streaming Transformations, Windowing, & Aggregations"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

The video below discusses how we can take streaming sources and transform them, group the observations and aggregate them, and how windowing is used to allow flexibility in how we do this. 

I highly recommend watching the video using the 'full' Panopto player. There is a 'pop out' button in the bottom right of the video to enter this viewer.

The notebook used in the video is available <a href = "https://jbpost2.github.io/ST-554-Big-Data-with-Python/04_Streaming_Data/Streaming_Data_Notebook.ipynb" target = "_blank">here</a>. You'll need to download this `.ipynb` file and upload it to your `JupyterHub` environment. Make sure that the kernel used to run the notebook is a `pyspark` kernel!

Remember, if you are off campus you should log in to the VPN and then you can [access our `JupyterHub`](https://jhub.cos.ncsu.edu/).


```{=html}
<iframe src="https://ncsu.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=baad418d-ece1-4cad-9d61-b2b1004a1b07&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="05-Transformations, Windowing, &amp; Aggregations" ></iframe>
```

## Notes

- <a href = "05-Transformations_Windowing_Aggregations.html" target = "_blank">HTML version</a>
- <a href = "PDFs/05-Transformations_Windowing_Aggregations.pdf" target = "_blank">PDF version</a>

Use the table of contents on the left or the arrows at the bottom of this page to navigate to the next learning material!